[package]
name = "rproxy"
version = "0.1.0"
authors = ["Rong Xian <rong.xian@gmail.com>"]
description = "Platform independent asynchronous udp/tcp proxy"
homepage = "https://github.com/glacierx/rproxy"
repository = "https://github.com/glacierx/rproxy"
readme = "README.md"
keywords = ["proxy", "tcp", "udp", "async"]
categories = ["command-line-utilities", "network-programming"]
license = "MIT"
edition="2018"

[dependencies]
getopts = "0.2"
rand = "0.7.3"
tokio= { version = "0.2.22", features = ["full"] }
futures= "0.3.5"
crossbeam="0.7.3"
log = { version = "0.4", features = ["std", "serde"] }